export { default as CreditCard } from './fill/credit-card'
export { default as ImageFill } from './fill/image'
export { default as Person } from './fill/person'
export { default as CreditCardOutline } from './outline/credit-card'
export { default as ImageOutline } from './outline/image'
export { default as PersonOutline } from './outline/person'
export { default as Trending } from './trending'
