import { PropsWithChildren } from 'react'

import { Typography } from '@tazalov/kebab-ui/components'
import { Header, Sidebar } from '@tazalov/kebab-ui/layout'
import clsx from 'clsx'
import Head from 'next/head'
import Link from 'next/link'
import { usePathname } from 'next/navigation'

import s from './MainLayout.module.scss'

import { sidebarItems } from '../../model/const/sidebarItems'

export const MainLayout = ({ children }: PropsWithChildren) => {
  const pathname = usePathname()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header>
        <Typography asComponent={Link} href="/">
          <Typography asComponent="span" variant="large">
            Inctagram
          </Typography>
          <Typography asComponent="span" variant="small">
            Super
          </Typography>
          <Typography asComponent="span" variant="smallSemiBold">
            Admin
          </Typography>
        </Typography>
      </Header>
      <div className={clsx(s.wrapper)}>
        <Sidebar.Root className={s.sidebar}>
          <Sidebar.List>
            {sidebarItems.map((el, i) => {
              const itemPath = typeof el.href === 'string' ? el.href : el.href.pathname

              const isActive = pathname === itemPath

              return (
                <Sidebar.Item key={`sidebar-item-${i}`}>
                  <Sidebar.ItemContent
                    asComponent={Link}
                    href={el.href}
                    isActive={isActive}
                    item={el}
                  />
                </Sidebar.Item>
              )
            })}
          </Sidebar.List>
        </Sidebar.Root>
        <main className={s.main}>{children}</main>
      </div>
    </>
  )
}
