import { PropsWithChildren } from 'react'

import { clsx } from '@tazalov/kebab-ui'
import Head from 'next/head'

import s from './MainLayout.module.scss'

import { CustomMobileSidebar } from '../CustomMobileSidebar/CustomMobileSidebar'
import { CustomSidebar } from '../CustomSidebar/CustomSidebar'
import { Header } from '../Header/Header'

type Props = {
  isHideSidebar?: boolean
} & PropsWithChildren

export const MainLayout = ({ children, isHideSidebar }: Props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <Header />
      <div className={clsx(s.wrapper)}>
        <CustomSidebar className={clsx(s.sidebar, { [s.hide]: isHideSidebar })} />
        <CustomMobileSidebar className={s.mobileSidebar} />
        <main className={s.main}>{children}</main>
      </div>
    </>
  )
}
